### ISSUE TITLE
Digging into structured data

### ISSUE THREAD

**Issue by blangenfeld** [ulfurinn/wongi-engine-elixir#1]
Hey @ulfurinn --

First: thank you for this library! It's been fun to play with retes for the first time. (A card game rules engine; what else?)

Had a thought while working with fields that contain structured data: the writing (and reading!) feels pretty verbose sometimes. Here's a contrived example... 👇

```elixir
# find everyone whose first profile photo is a jpg or png
# and generate a couple of facts about said photo
[
  forall: [
    has(var(:id), :profile, var(:profile)),
    filter(
      &(extract_path(&1[:profile], [:photos, 0, :mime_type]) in ["image/jpeg", "image/png"])
    ),
    assign(:photo_url, &extract_path(&1[:profile], [:photos, 0, :url])),
    assign(:photo_name, &extract_path(&1[:profile], [:photos, 0, :name]))
  ],
  do: [
    gen(var(:id), :profile_photo_url, var(:photo_url)),
    gen(var(:id), :profile_photo_name, var(:photo_name))
  ]
]
```

Something like Ecto's [json_extract_path/2](https://hexdocs.pm/ecto/Ecto.Query.API.html#json_extract_path/2) seems like it'd be a pretty good addition to the DSL. How do we feel about adding `var/2` to directly access data within a bound variable? 👇

```elixir
[
  forall: [
    has(var(:id), :profile, var(:profile)),
    in_list(var(:profile, [:photos, 0, :mime_type]), ["image/jpeg", "image/png"]),
    assign(:photo, var(:profile, [:photos, 0]))
  ],
  do: [
    gen(var(:id), :profile_photo_url, var(:photo, [:url])),
    gen(var(:id), :profile_photo_name, var(:photo, [:name]))
  ]
]
```

**Comment by ulfurinn** [comment]
Not super keen on extending `var` with such specific assumptions about the shape of the data, but maybe it could be some new function.

Also, the intended way to represent facts is to avoid injecting deep structured terms altogether and instead decompose them into a flat set of `{subject, predicate, object}`, which in your example would produce a graph like:

```
ID, profile, Profile
Profile, photo, Photo
Photo, index, 0
Photo, mime_type, ...
Photo, url, ...
Photo, name, ...
```

and you'd use some kind of surrogate value for the intermediate nodes, like IDs if you have them in the model, or generated refs. I might add helpers for that in the future.
